import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react';
import Nav from './nav';
import Fooder from '../components/fooder';




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',


}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark" style={{ colorScheme: "dark" }} >
      <body className={`${inter.className} dark custom-bg`}>
      <Suspense>
          <Nav />
      </Suspense>

      {children}
        <Fooder />
      </body>
    </html>
  )
}
